### ISSUE TITLE
Add locale filter

### ISSUE THREAD

**Issue by danielbergholz** [danielbergholz/techschool.dev#11]
Currently, when you select the default `en` locale, you only see courses that are in `en`. But if you select the `pt` locale, you see courses in `pt` AND `en`. It's a good solution for now, not gonna lie. If users start complaining about more control over the courses locale, then it's time to build this locale filter. Low priority for now

**Comment by kevinam99** [comment]
Opened a PR here for this. Hope it's right https://github.com/danielbergholz/techschool.dev/pull/20

**Comment by danielbergholz** [comment]
Thanks for your contribution @kevinam99! For now I don't think this filter is necessary, so I think I'm gonna close the issue for now and re-create in the future (if people ask for it)
