### ISSUE TITLE
Java course addition

### ISSUE THREAD

**Issue by LucasBergholz** [danielbergholz/techschool.dev#18]
I would like to contribute with the repositorie with a portuguese java course made by Dev Dojo. Here are the following links:

- Videos (Playlist): https://www.youtube.com/playlist?list=PL62G310vn6nFIsOCC0H-C2infYgwm8SWW
- Channel: https://www.youtube.com/@DevDojoBrasil
- Course ID: PL62G310vn6nFIsOCC0H-C2infYgwm8SWW
- Language: Java
- Channel Image Link: https://yt3.googleusercontent.com/ytc/AIf8zZTfszOrW6W-5H182FAQPUPbhm4S6-jViyJS8LEi=s176-c-k-c0x00ffffff-no-rj

**Comment by danielbergholz** [comment]
Thanks for the suggestion! I just added multiple courses from DevDojo
