### ISSUE TITLE
Add your own videos from your YouTube channel

### ISSUE THREAD

**Issue by martinbra** [danielbergholz/techschool.dev#30]
This would probably require you to add a filter by course speak language, but if people say your content is good, why not?

**Comment by danielbergholz** [comment]
Hey Martin! Thank you for your contribution!
Could you be a little bit more clear about this? I'm not sure I understand 😅. You are suggesting creating a filter for YouTube channels?

**Comment by broccoder** [comment]
> Could you be a little bit more clear about this? I'm not sure I understand 😅. You are suggesting creating a filter for YouTube channels?

I think he means being able to filter by video language. Currently, you can only filter by programming language, framework and tool. He means to say that you should add a filter for human language. For example, you could select English and only English courses will show up, and if you select Spanish then only spanish courses will show up, otherwise all courses will show up.

**Comment by danielbergholz** [comment]
> I think he means being able to filter by video language. Currently, you can only filter by programming language, framework and tool. He means to say that you should add a filter for human language. For example, you could select English and only English courses will show up, and if you select Spanish then only spanish courses will show up, otherwise all courses will show up.

Ah got it, thanks for explaining. I don't think we need a filter for human language right now TBH (maybe in the future?), TechSchool only offers 2 languages, and to filter the Portuguese courses all you need is to access the website normally in English. But maybe @martinbra can explain a little bit more here

**Comment by martinbra** [comment]
That's it. I just couldn't find your Portuguese channel on the website, as
I always leave my browser in English by default.

**Comment by danielbergholz** [comment]
> That's it. I just couldn't find your Portuguese channel on the website, as
> 
> I always leave my browser in English by default.

Ah you mean literally MY channel 😅. Thanks for the interest in watching my content! But to be honest I don't want any method to find a channel easier than other ones. In some way I would be creating my own algorithm inside TechSchool to find my channel only. Even thought I'm the creator of the project, if someone wants to find my channel he needs to filter by programming language or framework and then my channel would show up in the results like any other one. A fair and equal chance for everyone.

Or you could simply find about my website on twitter for example, and then click on my YouTube link there.

PS: My content is in Portuguese right now but I'll convert it to English soon
