### ISSUE TITLE
Add sponsors section to homepage

### ISSUE THREAD

**Issue by danielbergholz** [danielbergholz/techschool.dev#33]
The `Techschool.GitHub` module (`lib/techschool/github.ex`) is already created, we just need to create a new function `get_sponsors` (similar to `get_contributors`) and add it to the homepage (`lib/techschool_web/live/page_live/home.ex`)

**Comment by danielbergholz** [comment]
Oh, and since there are no sponsors currently, feel free to hide the section and only show it if the sponsors array is not empty

**Comment by dmitry-sidorov** [comment]
@danielbergholz Hey, man! March 7 (issue opened) is my wife's birthday! 😆 I guess, I should work on this feature 😅

**Comment by dmitry-sidorov** [comment]
@danielbergholz Looks like there is no rest endpoint to get the list of sponsors for given repository.
https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository

I also found Github Sponsor API exists. https://github.com/orgs/community/discussions/3818
Two things I concern about:

1. Sponsor API is GraphQL. That means, we should add third-party library to handle GraphQL. Absinthe, for example:
https://github.com/absinthe-graphql/absinthe
2. It's very likely you should send GraphQL sponsors request with some kind of auth token (GPG Key or whatever Github provides). Sponsors list could be treated as sensitive information and will require authorization.

Do you have any github sponsors use cases?

**Comment by danielbergholz** [comment]
> @danielbergholz Hey, man! March 7 (issue opened) is my wife's birthday! 😆 I guess, I should work on this feature 😅

Nice coincidence!

> @danielbergholz Looks like there is no rest endpoint to get the list of sponsors for given repository.

I just checked, and I can confirm there is no API endpoint for getting the sponsors of a specific user, which is a shame. And being 100% honest here, I don't think installing Absinthe and then interacting with a GraphQL API is worth it, it's too much work. I'll close this issue for now
