### ISSUE TITLE
Personal Preference for images on courses section

### ISSUE THREAD

**Issue by Ragudos** [danielbergholz/techschool.dev#34]
Can we fullscreen the cover image on each card in the courses section? Also make the cards a tad bit larger on mobile. I'm loving the UI!

![Screenshot_2024-03-07-15-46-40-78_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/danielbergholz/techschool.dev/assets/133567781/eff95b68-ba53-424f-a9e1-456b1d2636d4)

**Comment by danielbergholz** [comment]
I'm going to be honest, I tested this locally and it didn't look good 😅
The image occupying more space ended up showing fewer courses on the screen. Instead of showing 1 and a half courses, it barely showed 1

**Comment by hinode-codes** [comment]
> I'm going to be honest, I tested this locally and it didn't look good 😅 The image occupying more space ended up showing fewer courses on the screen. Instead of showing 1 and a half courses, it barely showed 1

Aw, I see. I guess it depends on the content. Thank you for trying it out before closing!
