### ISSUE TITLE
Add "no courses that match search results" text and remove the "load more" button when nothing matches the search/category query.

### ISSUE THREAD

**Issue by Ragudos** [danielbergholz/techschool.dev#35]
![Screenshot_2024-03-07-15-54-56-35_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/danielbergholz/techschool.dev/assets/133567781/af3d85c5-806c-40fd-b433-9b7adba182c5)

**Comment by lcezermf** [comment]
Hey, can I pick this? @Ragudos @danielbergholz

**Comment by hinode-codes** [comment]
It's fine for me. I suggest waiting for @danielbergholz to respond since I'm new in this repo.

**Comment by danielbergholz** [comment]
Sure @lcezermf, that would be great! LMK if you have any questions 🤝

**Comment by lcezermf** [comment]
NP. I will dig into the code a little more and do a draft PR until the next week.

**Comment by danielbergholz** [comment]
Awesome @lcezermf, thank you!

**Comment by lcezermf** [comment]
@danielbergholz I started working on something, just wanna check something the idea is to keep using `stream` to hold the courses within the search page, correct? Is there any advantage over using the regular `assign(socket, :data, values)`?

**Comment by danielbergholz** [comment]
Some people say it's better for memory usage, especially when dealing with lots of records from the DB, but I'm open to suggestions

**Comment by lcezermf** [comment]
Not a problem! I was just curious cause I have never used that before (my current project uses a lower version) and I got the unit tests working but the feature feels odd cause seem the result on the page never get "empty", but I will try a little more with streams and see how it goes.
