### ISSUE TITLE
Find a way to add text courses

### ISSUE THREAD

**Issue by danielbergholz** [danielbergholz/techschool.dev#37]
Find a way to add text courses instead of a YouTube video course. This will likely involve:

- Creating a new DB table
- Creating a `text_card.html.heex` component
- Listing text courses alongside youtube courses on the `/courses` route

**Comment by lcezermf** [comment]
In this case the table `courses` has to be updated to allow possible `channel_id` and `youtube_course_id` blank/nil is that correct?

**Comment by danielbergholz** [comment]
That could be an option, but I think I'm going to create a separate table, to avoid this type of "inconsistency"

**Comment by danielbergholz** [comment]
I ended up creating a new context for this called `Platforms` (for external platforms/websites like freeCodeCamp, The Odin Project)
