### ISSUE TITLE
Create new DB table and filter for `fundamentals`

### ISSUE THREAD

**Issue by danielbergholz** [danielbergholz/techschool.dev#51]
Before learning a programming language or framework, it is extremely important to study the fundamentals of computer science, networking, algorithms etc.

So let's create a new DB table and filter component for `fundamentals`, which I think is an appropriate name for this (but I'm open to suggestions 👀).

The schema for it should be almost equal to the `language` and `framework`, but without the `image_url` field (I don't think I'm ever gonna show images for these). So a `name` field and a `many_to_many` relationship with `courses`

**Comment by lcezermf** [comment]
It seems a doable approach.

**Comment by danielbergholz** [comment]
Hey @lcezermf! I actually already finished this work, but forgot to close the issue 😅
