### ISSUE TITLE
Write more LiveView tests

### ISSUE THREAD

**Issue by danielbergholz** [danielbergholz/techschool.dev#66]
There are a couple of things that I still need to write system tests for:

- Changing the locale to `pt` also changes the `platform` text to `description_pt` on the courses page
- Changing the locale to `pt` also changes the `bootcamp` text to `description_pt` on the bootcamps `index` and `show` pages
- Filtering a course by programming language and framework on the courses page

Any more ideas are welcome! I think I have enough tests for the contexts, I wanted to have more E2E tests now

**Comment by dmitry-sidorov** [comment]
@danielbergholz Hey, man! 
>   I wanted to have more E2E tests now

What do you mean? 
E2E tests based on ExUnit or some kind of UI tests using test frameworks, e.g. Cypress or Playwright?

**Comment by danielbergholz** [comment]
Hey! Yeah, E2E LiveView tests with ExUnit, just like all the ones inside `test/techschool_web/live`. As an example, here is a test to check if the platforms are using the `description_pt` if the `pt` is selected in the URL:

<img width="638" alt="image" src="https://github.com/danielbergholz/techschool.dev/assets/39206652/9bb48c75-3f02-4335-94d1-98361f7e38d6">

I'm also open to test more stuff in LiveView if you think there is anything else missing
