### ISSUE TITLE
Don't run CI if only JSON files were changed

### ISSUE THREAD

**Issue by danielbergholz** [danielbergholz/techschool.dev#67]
The majority of the PRs to this repo will be course additions, with only JSON files being changed. It doesn't make sense to run tests again if the codebase itself didn't change. A couple of possible approaches here:

- Disable CI if only JSON files were changed
- Disable CI if only files from `priv/repo/data` were changed

**Comment by kalogs-c** [comment]
I dont think this is necessary, since it should be tests to validate if the json files was modified correctly

**Comment by danielbergholz** [comment]
Makes sense! I need to write a couple of extra tests to make sure the JSON is using the correct format, because right now I'm not testing the `seeding` to the DB. I test that locally on my machine before deploying

**Comment by danielbergholz** [comment]
I'm closing this issue and creating another one to validate the JSON files
